//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class volunteer_language
    {
        public int code_volunteer_language { get; set; }
        public int code_language { get; set; }
        public string id_volunteer { get; set; }
    
        public virtual language language { get; set; }
        public virtual volunteer volunteer { get; set; }
    }
}
